FROM python:3.6

RUN pip install configparser
RUN pip install pika
RUN pip install Click
RUN pip install Flask
RUN pip install Flask-Cors
RUN pip install Jinja2
RUN pip install numpy==1.16.0
RUN pip install pandas==0.23.4
RUN pip install psycopg2
RUN pip install python-dateutil
RUN pip install pytz

RUN pip install SQLAlchemy
RUN pip install telnetlib3
RUN pip install Werkzeug
RUN pip install pysftp
RUN pip install pika
RUN pip install psutil
RUN pip install paho-mqtt
RUN pip install pip --upgrade
RUN apt update -y
RUN apt install gcc g++ gfortran build-essential gfortran libatlas-base-dev -y
RUN apt-get install libhdf5-dev -y
RUN apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev -y
RUN apt-get install nano -y
RUN pip install scipy==1.2.0
RUN pip install statsmodels
RUN pip install tables
RUN pip install install flask_monitoringdashboard
